# Generated by Django 4.2.4 on 2023-08-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_date_user_field1_user_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='field2',
        ),
    ]
